spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/twins_store?characterEncoding=UTF-8&amp;allowMultiQueries=true
    data-username: root
    password: 123456
  jpa:
    generate-ddl: true
    hibernate:
      naming:
        implicit-strategy: com.twins.store.common.support.NamingStrategy
